name: "Test Content Checker"

on:
  push:

jobs:
  check-content:
    name: "Check the content of the lesson"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone imls-tools into a subfolder
        uses: actions/checkout@v2
        with:
          repository: ucla-imls-open-sci/imls-tools
          path: imls-tools

      - name: Make script executable (only if needed)
        run: chmod +x imls-tools/content-checker/content_checker.sh

      - name: Run the Content Checker
        run: |
          imls-tools/content-checker/content_checker.sh -P .
