name: "Test Content Checker"

on:
  push:

jobs:
  check-content:
    name: "Check the content of the lesson"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone imls-tools into a subfolder
        run: |
          git clone https://github.com/ucla-imls-open-sci/imls-tools tools-folder

      - name: Make script executable (only if needed)
        run: chmod +x tools-folder/content-checker/content_checker.sh

      - name: Run the Content Checker
        run: |
          ./tools-folder/content-checker/content_checker.sh -P .
